## Exercise 1 : Linear Reggression 

In [48]:
import numpy as np # fundamental package for scientific computing in Python
import matplotlib.pyplot as plt #

plt.style.use('seaborn-whitegrid')


In [7]:
# Matrix of 5 by 5 fill of zeroes 
Zero_Matrix= np.zeros(5, dtype=np.int)
Zero_Matrix

array([0, 0, 0, 0, 0])

In [27]:
def Warmup():
    return(np.identity(5,dtype=np.int))

In [28]:
## calling our simple identity function 
Warmup()

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [34]:
# Load data from txt file 

data = np.loadtxt('ex1/ex1data1.txt', delimiter=',')
data

array([[  6.1101 ,  17.592  ],
       [  5.5277 ,   9.1302 ],
       [  8.5186 ,  13.662  ],
       [  7.0032 ,  11.854  ],
       [  5.8598 ,   6.8233 ],
       [  8.3829 ,  11.886  ],
       [  7.4764 ,   4.3483 ],
       [  8.5781 ,  12.     ],
       [  6.4862 ,   6.5987 ],
       [  5.0546 ,   3.8166 ],
       [  5.7107 ,   3.2522 ],
       [ 14.164  ,  15.505  ],
       [  5.734  ,   3.1551 ],
       [  8.4084 ,   7.2258 ],
       [  5.6407 ,   0.71618],
       [  5.3794 ,   3.5129 ],
       [  6.3654 ,   5.3048 ],
       [  5.1301 ,   0.56077],
       [  6.4296 ,   3.6518 ],
       [  7.0708 ,   5.3893 ],
       [  6.1891 ,   3.1386 ],
       [ 20.27   ,  21.767  ],
       [  5.4901 ,   4.263  ],
       [  6.3261 ,   5.1875 ],
       [  5.5649 ,   3.0825 ],
       [ 18.945  ,  22.638  ],
       [ 12.828  ,  13.501  ],
       [ 10.957  ,   7.0467 ],
       [ 13.176  ,  14.692  ],
       [ 22.203  ,  24.147  ],
       [  5.2524 ,  -1.22   ],
       [  6.5894 ,   5.9966 ],
       [

In [44]:
X = data[:,0] # First colum
Y = data[:,1] # Second Column
m = data.shape[0] # Number of traning samples

In [51]:
plt.scatter(X, Y, s = 30 ,alpha=0.5, marker= 'x') 
plt.ylabel("Profit in $10,000")
plt.xlabel("Population of City in 10,000s")
plt.title('training data')



97